[pytest]
addopts = -p no:toolbelt --ckan-ini=test.ini
filterwarnings =
    ignore::DeprecationWarning:pkg_resources
    ignore::DeprecationWarning:distutils
    ignore::DeprecationWarning:cgi
    ignore::DeprecationWarning:passlib
    ignore::DeprecationWarning:ckan
    ignore::DeprecationWarning:ckanext
    ignore::sqlalchemy.exc.SADeprecationWarning
    ignore::sqlalchemy.exc.LegacyAPIWarning
    ignore::DeprecationWarning:sqlalchemy
